### ISSUE TITLE
IndexError when fetching complete collection

### ISSUE THREAD

**Issue by edsu** [umd-mith/hathitables#1]
Not sure why this is happening when the collection is completely pulled down:

```
(hathitables)ubuntu@ip-10-39-110-115:~/hathitables$ ./hathitables.py 1316980598 > 1316980598.csv
Traceback (most recent call last):
  File "./hathitables.py", line 144, in <module>

  File "./hathitables.py", line 104, in write_csv
    item.get('creator'),
  File "./hathitables.py", line 94, in volumes
    writer = csv.writer(fh)
  File "/home/ubuntu/.virtualenvs/hathitables/local/lib/python2.7/site-packages/hathilda.py", line 30, in get_volume
    first_id = list(response['records'].keys())[0]
IndexError: list index out of range
```

**Comment by edsu** [comment]
This got fixed by making things simpler...
