### ISSUE TITLE
HathiTrust API: Connection aborted 

### ISSUE THREAD

**Issue by edsu** [umd-mith/hathitables#2]
Seeing this when talking to the HathiTrust API:

```
Traceback (most recent call last):
  File "./hathitables.py", line 157, in <module>
    c.write_csv(sys.stdout)
  File "./hathitables.py", line 101, in write_csv
    for item in self.volumes():
  File "./hathitables.py", line 88, in volumes
    yield hathilda.get_volume(vol_id)
  File "/home/ubuntu/.virtualenvs/hathitables/local/lib/python2.7/site-packages/hathilda.py", line 27, in get_volume
    vol = _extract_vol(response, vol_id)
  File "/home/ubuntu/.virtualenvs/hathitables/local/lib/python2.7/site-packages/hathilda.py", line 56, in _extract_vol
    for item in response['items']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

with this in the log:

```
INFO:root:fetching volume coo.31924003430430
INFO:root:fetching volume mdp.39015056246336
INFO:root:fetching volume mdp.39015076236937
INFO:root:fetching volume inu.32000005639960
INFO:root:fetching volume mdp.39015082988752
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /cgi/pt?id=mdp.39015082988752
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (9): babel.hathitrust.org
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: catalog.hathitrust.org
```

It ought to be possible to catch errors like this and backoff from doing a bunch of requests in a row? Although it looks like this might need to go in hathilda...

**Comment by edsu** [comment]
Should be poss

**Comment by edsu** [comment]
Using [backoff](https://github.com/litl/backoff) to catch errors from the API.
